services:
  gsm_agent_dev:
    image: ghcr.io/ten-framework/ten_agent_build:0.5.0
    container_name: gsm_agent_dev
    platform: linux/amd64
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${GRAPH_DESIGNER_SERVER_PORT}:${GRAPH_DESIGNER_SERVER_PORT}"
      - "8088:8086"
    volumes:
      - ./:/app
      - ${LOG_PATH}:${LOG_PATH}
    working_dir: /app
    env_file:
      - .env
    networks:
      - gsm_agent_network
  gsm_agent_playground:
    image: ghcr.io/ten-framework/ten_agent_playground:0.8.0-147-g15052ec
    container_name: gsm_agent_playground
    restart: always
    ports:
      - "3018:3000"
    networks:
      - gsm_agent_network
    environment:
      - AGENT_SERVER_URL=http://gsm_agent_dev:8086
      - TEN_DEV_SERVER_URL=http://gsm_agent_dev:49483
  gsm_agent_demo:
    image: ghcr.io/ten-framework/ten_agent_demo:0.8.0-34-gfc5b116
    container_name: gsm_agent_demo
    restart: always
    ports:
      - "3019:3000"
    networks:
      - gsm_agent_network
    environment:
      - AGENT_SERVER_URL=http://gsm_agent_dev:8086
  # gsm_graph_designer:
  #   image: ghcr.io/ten-framework/ten_graph_designer:4cc33b8
  #   container_name: gsm_graph_designer
  #   restart: always
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - gsm_agent_network
  #   environment:
  #     - TEN_DEV_SERVER_URL=http://gsm_agent_dev:49483
networks:
  gsm_agent_network:
    driver: bridge
